CREATE DATABASE STUDENT_MANAGEMENT
GO

USE STUDENT_MANAGEMENT

-- create tables
CREATE TABLE dbo.Khoa
(
	MaKhoa VARCHAR(10) PRIMARY KEY,
	TenKhoa NVARCHAR(100) NOT NULL,
	NamThanhLap DATE NUll
)
GO

CREATE TABLE dbo.KhoaHoc
(
	MaKoaHoc VARCHAR(10) PRIMARY KEY,
	NamBatDau DATE NULL,
	NamKetThuc DATE NULL
)
GO

CREATE TABLE dbo.ChuongTrinhHoc
(
	MaCT VARCHAR(10) PRIMARY KEY,
	TenCT NVARCHAR(100) NOT NULL
)
GO

CREATE TABLE dbo.Lop
(
	MaLop VARCHAR(10) PRIMARY KEY,
	MaKhoa VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES dbo.Khoa(MaKhoa),
	MaKhoaHoc VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES dbo.KhoaHoc(MaKoaHoc),
	MaCT VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES dbo.ChuongTrinhHoc(MaCT),
	STT INT NOT NULL
)
GO

CREATE TABLE dbo.SinhVien
(
	MaSV VARCHAR(10) PRIMARY KEY,
	HoTen NVARCHAR(100) NOT NULL,
	NamSinh DATE NOT NULL,
	DanToc NVARCHAR(20) NULL,
	MaLop VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES dbo.Lop(MaLop)
)
GO 

CREATE TABLE dbo.MonHoc
(
	MaMH VARCHAR(10) PRIMARY KEY,
	MaKhoa VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES dbo.Khoa(MaKhoa),
	TenMH NVARCHAR(100) NOT NULL
)
GO

CREATE TABLE dbo.KetQua
(
	MaSV VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES dbo.SinhVien(MaSV),
	MaMH VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES dbo.MonHoc(MaMH),
	LanThi INT NOT NULL,
	DiemThi FLOAT NULL

	PRIMARY KEY(MaSV, MaMH, LanThi)
)
GO

CREATE TABLE dbo.GiangKhoa
(
	MaCT VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES dbo.ChuongTrinhHoc(MaCT),
	MaKhoa VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES dbo.Khoa(MaKhoa),
	MaMH VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES dbo.MonHoc(MaMH),
	NamHoc DATE NOT NULL,
	HocKy INT NOT NULL,
	SoTietLyThuyet INT NOT NULL,
	SoTietThucHanh INT NOT NULL,
	SoTinChi INT NOT NULL

	PRIMARY KEY(MaCT, MaKhoa, MaMH, NamHoc)
)
GO